# Generated by Django 6.0.5 on 2026-08-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('location', models.CharField(max_length=80)),
                ('category', models.CharField(choices=[('Facilities', 'Facilities'), ('Technology', 'Technology'), ('Campus life', 'Campus life'), ('Transport', 'Transport'), ('Safety', 'Safety')], default='Facilities', max_length=20)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In progress', 'In progress'), ('Resolved', 'Resolved')], default='Open', max_length=20)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10)),
                ('reporter', models.CharField(default='You', max_length=60)),
                ('description', models.TextField(blank=True, default='No additional details provided.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
