# Generated by Django 5.2.17 on 2026-08-12 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('campus_life', 'Campus Life & Amenities'), ('classroom_equipment', 'Classroom / Lab Equipment'), ('electrical', 'Electrical / AC Fault'), ('cleanliness', 'Cleanliness & Sanitation'), ('other', 'Other')], default='campus_life', max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='issue_attachments/')),
                ('status', models.CharField(choices=[('pending', 'Pending Admin Review'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('admin_response', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='The user who submitted the issue.', on_delete=django.db.models.deletion.CASCADE, related_name='campus_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Campus issues',
                'ordering': ['-created_at'],
            },
        ),
    ]
