# Generated by Django 5.2.17 on 2026-08-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_user_campus_id_user_registration_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPasskey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'admin passkey',
                'verbose_name_plural': 'admin passkeys',
                'ordering': ['code'],
            },
        ),
    ]
