# Generated by Django 5.2.17 on 2026-08-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_seed_admin_passkeys'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='batch',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
