# Generated by Django 5.2.17 on 2026-08-07 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_routine_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('campus_id', models.CharField(blank=True, max_length=30)),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Faculty'), ('admin', 'Admin')], default='student', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, help_text='The account created by this registration (if any).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registration request',
                'verbose_name_plural': 'registration requests',
                'ordering': ['-applied_at'],
            },
        ),
    ]
