# Generated by Django 5.2.17 on 2026-08-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_user_full_name_and_unique_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=10)),
                ('batch', models.CharField(max_length=10)),
                ('day', models.CharField(choices=[('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday')], max_length=3)),
                ('time_slot', models.CharField(blank=True, max_length=40)),
                ('subject', models.CharField(max_length=100)),
                ('faculty', models.CharField(blank=True, max_length=100)),
                ('room', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Routine slots',
                'ordering': ['day', 'time_slot'],
            },
        ),
    ]
