# Generated by Django 5.2.17 on 2026-08-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_routineslot_section_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routineslot',
            name='section',
            field=models.CharField(default='A', max_length=10),
        ),
    ]
