# Generated by Django 5.2.17 on 2026-08-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_routineslot_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routineslot',
            name='day',
            field=models.CharField(choices=[('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('SAT', 'Saturday')], max_length=3),
        ),
    ]
