# Generated by Django 5.2.17 on 2026-08-11 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_routineslot_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraClassRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=10)),
                ('batch', models.CharField(max_length=10)),
                ('section', models.CharField(default='A', max_length=10)),
                ('subject', models.CharField(max_length=100)),
                ('reason', models.CharField(choices=[('makeup', 'Makeup Class'), ('extra', 'Extra Class'), ('exam', 'Exam Reschedule')], default='extra', max_length=20)),
                ('day', models.CharField(choices=[('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('SAT', 'Saturday')], max_length=3)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending Admin Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_class_requests', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_class_requests', to='booking.room')),
            ],
            options={
                'verbose_name_plural': 'Extra class requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
