# Generated by Django 5.2.17 on 2026-08-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_extraclassrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraclassrequest',
            name='trashed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
