# Generated by Django 5.2.17 on 2026-08-11 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_extraclassrequest_trashed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('important', 'Important'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('target_role', models.CharField(choices=[('all', 'All Users'), ('faculty', 'Faculty Only'), ('student', 'Students Only')], default='all', max_length=20)),
                ('department', models.CharField(blank=True, max_length=10)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='notice_attachments/')),
                ('pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notices',
                'ordering': ['-pinned', '-created_at'],
            },
        ),
    ]
