# Generated by Django 5.2.17 on 2026-08-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='batch',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='notice',
            name='section',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
