# Generated by Django 5.2.17 on 2026-08-11 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_notice_batch_notice_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraclassrequest',
            name='is_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extraclassrequest',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='extraclassrequest',
            name='reason',
            field=models.CharField(choices=[('makeup', 'Makeup Class'), ('extra', 'Extra Class'), ('exam', 'Exam Reschedule'), ('event', 'Special Event')], default='extra', max_length=20),
        ),
        migrations.CreateModel(
            name='DisplacedClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=10)),
                ('batch', models.CharField(blank=True, max_length=10)),
                ('section', models.CharField(default='A', max_length=10)),
                ('day', models.CharField(choices=[('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('SAT', 'Saturday')], max_length=3)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending Reschedule'), ('rescheduled', 'Rescheduled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(blank=True, help_text='The teacher whose regular class was pushed out (matched by name).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='displaced_classes', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='displacements', to='booking.extraclassrequest')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='displacements', to='booking.room')),
                ('slot', models.ForeignKey(blank=True, help_text='The master-routine slot that was overridden.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='displacements', to='booking.routineslot')),
            ],
            options={
                'verbose_name_plural': 'Displaced classes',
                'ordering': ['-created_at'],
            },
        ),
    ]
