# Generated by Django 5.2.17 on 2026-08-12 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_remap_room_buildings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=10)),
                ('batch', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=10)),
                ('course_code', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('reason', models.CharField(choices=[('faculty_unavailable', 'Faculty Unavailable'), ('emergency', 'Emergency'), ('official_meeting', 'Official Department Meeting'), ('rescheduled', 'Rescheduled to another slot'), ('other', 'Other')], default='faculty_unavailable', max_length=30)),
                ('reason_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(help_text='The teacher who cancelled the class.', on_delete=django.db.models.deletion.CASCADE, related_name='class_cancellations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'class cancellation',
                'verbose_name_plural': 'class cancellations',
                'ordering': ['-created_at'],
            },
        ),
    ]
