# Generated by Django 5.2.17 on 2026-08-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_user_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_cr',
            field=models.BooleanField(default=False),
        ),
    ]
